<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Mixed-Effect Models</title>

<script src="site_libs/header-attrs-2.18/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/readable.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>





<style type="text/css">
/* for pandoc --citeproc since 2.11 */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Statistical Modeling Examples in R</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Examples
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="lm.html">linear models</a>
    </li>
    <li>
      <a href="lrm.html">logistic regression models</a>
    </li>
    <li>
      <a href="cm.html">count models</a>
    </li>
    <li>
      <a href="lme.html">mixed-effect models</a>
    </li>
  </ul>
</li>
<li>
  <a href="about.html">About</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Mixed-Effect Models</h1>

</div>


<div id="multilevel-model-two-levels" class="section level3">
<h3>Multilevel model: two levels</h3>
<p>The <code>eggprod</code> data in the faraway package contains data on
egg production. <span class="citation">(Faraway 2016)</span> Six pullets
(young hens) were placed into each of 12 pens. Four blocks were formed
from groups of 3 pens based on location. Three treatments were applied.
The number of eggs produced was recorded. Start by visualizing the
distribution of eggs produced split by blocks and treatment.</p>
<pre class="r"><code>library(faraway)
data(&quot;eggprod&quot;)

library(ggplot2)
# Plotting eggs ~ treat
ggplot(eggprod, aes(x=treat, y=eggs, color = treat)) + # Plotting eggs~treat, color by treat
  geom_jitter(position=position_jitter(0.2)) + # Creating a jitter plot,  staggering groups
  coord_flip() + # Flipping x and y coordinates to mimic Base R plotting
  theme_classic() # Using classic theme</code></pre>
<p><img src="lme_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<pre class="r"><code># Plotting eggs ~ block
ggplot(eggprod, aes(x=block, y=eggs, color = block)) + # Plotting eggs~treat, color by treat
  geom_jitter(position=position_jitter(0.2)) + # Creating a jitter plot,  staggering groups
  coord_flip() + # Flipping x and y coordinates to mimic Base R plotting
  theme_classic() # Using classic theme</code></pre>
<p><img src="lme_files/figure-html/unnamed-chunk-1-2.png" width="672" /></p>
<p>This shows visually that treatment O may have produced fewer eggs
than treatment F or E whose distributions are more similar and closer to
one another. The distributions of eggs produced by each block seem to
overlap and are very similar to one another.</p>
<p>Now, we model the number of eggs produced with <code>treat</code> as
a fixed effect and <code>block</code> as a random effect. <span
class="citation">(Faraway 2006)</span> Does <code>treat</code> appear to
affect the number of eggs, and if so, which treatment seems
superior?</p>
<pre class="r"><code>library(lme4)
m &lt;- lmer(eggs ~ treat + (1|block), data = eggprod)
summary(m)</code></pre>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: eggs ~ treat + (1 | block)
##    Data: eggprod
## 
## REML criterion at convergence: 85.4
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.71233 -0.47453 -0.02845  0.64196  1.42942 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  block    (Intercept) 129.9    11.40   
##  Residual             386.9    19.67   
## Number of obs: 12, groups:  block, 4
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   349.00      11.37  30.702
## treatF         -6.25      13.91  -0.449
## treatO        -42.50      13.91  -3.056
## 
## Correlation of Fixed Effects:
##        (Intr) treatF
## treatF -0.612       
## treatO -0.612  0.500</code></pre>
<pre class="r"><code>library(performance)
icc(m)</code></pre>
<pre><code>## # Intraclass Correlation Coefficient
## 
##     Adjusted ICC: 0.251
##   Unadjusted ICC: 0.144</code></pre>
<pre class="r"><code>VarCorr(m)</code></pre>
<pre><code>##  Groups   Name        Std.Dev.
##  block    (Intercept) 11.399  
##  Residual             19.670</code></pre>
<p>The likeness of egg production in the same block is .25. The
variation around the intercept is 11.40 across blocks. The intercept
fixed effect is the grand mean of eggs across the entire sample when
treat = “E”. The treatF and treatO fixed effects can be interpreted as
the difference in means (e.g., treatE - treatF). Therefore, treatF
produces 6.25 less mean egg production and treatO produces 42.50 less
mean egg production.</p>
<p>This is further substantiated by looking at the means by treatment.
Observed means of eggs by treat:</p>
<pre class="r"><code>tapply(eggprod$eggs, eggprod$treat, mean)</code></pre>
<pre><code>##      E      F      O 
## 349.00 342.75 306.50</code></pre>
<p>Pairwise comparisons, adjusted p-values and confidence intervals:</p>
<pre class="r"><code>library(emmeans)
emmeans(m, pairwise ~ treat)</code></pre>
<pre><code>## $emmeans
##  treat emmean   SE   df lower.CL upper.CL
##  E        349 11.4 7.99      323      375
##  F        343 11.4 7.99      317      369
##  O        306 11.4 7.99      280      333
## 
## Degrees-of-freedom method: kenward-roger 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast estimate   SE df t.ratio p.value
##  E - F        6.25 13.9  6   0.449  0.8965
##  E - O       42.50 13.9  6   3.056  0.0508
##  F - O       36.25 13.9  6   2.606  0.0892
## 
## Degrees-of-freedom method: kenward-roger 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<pre class="r"><code>emmeans(m, pairwise ~ treat) |&gt; confint()</code></pre>
<pre><code>## $emmeans
##  treat emmean   SE   df lower.CL upper.CL
##  E        349 11.4 7.99      323      375
##  F        343 11.4 7.99      317      369
##  O        306 11.4 7.99      280      333
## 
## Degrees-of-freedom method: kenward-roger 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast estimate   SE df lower.CL upper.CL
##  E - F        6.25 13.9  6  -36.426     48.9
##  E - O       42.50 13.9  6   -0.176     85.2
##  F - O       36.25 13.9  6   -6.426     78.9
## 
## Degrees-of-freedom method: kenward-roger 
## Confidence level used: 0.95 
## Conf-level adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p>An effect plot:</p>
<pre class="r"><code>library(ggeffects)
ggpredict(m, terms = ~ treat) |&gt; plot(add.data = TRUE)</code></pre>
<p><img src="lme_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>We can now assess model fit and significance of predictors.</p>
<pre class="r"><code>car::Anova(m)</code></pre>
<pre><code>## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: eggs
##        Chisq Df Pr(&gt;Chisq)   
## treat 10.887  2   0.004324 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>library(lmerTest)
summary(m)</code></pre>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: eggs ~ treat + (1 | block)
##    Data: eggprod
## 
## REML criterion at convergence: 85.4
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.71233 -0.47453 -0.02845  0.64196  1.42942 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  block    (Intercept) 129.9    11.40   
##  Residual             386.9    19.67   
## Number of obs: 12, groups:  block, 4
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   349.00      11.37  30.702
## treatF         -6.25      13.91  -0.449
## treatO        -42.50      13.91  -3.056
## 
## Correlation of Fixed Effects:
##        (Intr) treatF
## treatF -0.612       
## treatO -0.612  0.500</code></pre>
<p>Running a <span class="math inline">\(\chi^2\)</span> test on the
model, we see that the model including treat is a better fit (<span
class="math inline">\(\chi^2(2,N = 12) = 10.887, p &lt; .01\)</span>)
than the null model (intercept only). By loading the
<code>lmerTest</code> package, we can see in the summary that
specifically, treatment O is significant less than treatment E.</p>
<pre class="r"><code># normality of residuals; looks good
lattice::qqmath(m)</code></pre>
<p><img src="lme_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code># constant variance; one pretty big residual (model predicts about 335 but the observed value is closer to 300)
plot(m)</code></pre>
<p><img src="lme_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
<pre class="r"><code># constant variance within treatment levels; TreatF has a lot more variability
plot(m, treat ~ resid(.))</code></pre>
<p><img src="lme_files/figure-html/unnamed-chunk-7-3.png" width="672" /></p>
</div>
<div id="repeated-measures-model" class="section level3">
<h3>Repeated-Measures model</h3>
<p>The book <em>Linear Mixed Models</em> presents a study on rat brains
<span class="citation">(West, Welch, and Galecki 2015)</span>. In this
study, five rats had three regions of their brains measured for
“activation” after two different treatments. Since all rats received
both treatments and had the same three regions measured both times, this
is a <em>repeated-measures</em> analysis. Of interest is how the numeric
dependent variable, activate, changes based on treatment and brain
region.</p>
<p>The data is available in the file “rat_brain.dat”. We can import this
file using the <code>read.table()</code> function. We set
<code>header = TRUE</code> because the first row of the data contains
column headers.</p>
<pre class="r"><code>rats &lt;- read.table(&quot;data/rat_brain.dat&quot;, header = TRUE)</code></pre>
<p>The animal column contains the id for each rat. Below we use the
<code>head()</code> function to view the first six rows of data. Notice
the first rat, R111097, has one measure for each combination of
treatment and region. This is why we refer to this as repeated-measures
data.</p>
<pre class="r"><code>head(rats)</code></pre>
<pre><code>##    animal treatment region activate
## 1 R111097         1      1   366.19
## 2 R111097         1      2   199.31
## 3 R111097         1      3   187.11
## 4 R111097         2      1   371.71
## 5 R111097         2      2   302.02
## 6 R111097         2      3   449.70</code></pre>
</div>
<div id="longitudinal-model" class="section level3">
<h3>Longitudinal model</h3>
<p>The text <em>Statistical Methods for the Analysis of Repeated
Measurements</em> <span class="citation">(Davis 2002)</span> presents
data on plasma inorganic phosphate measurements for 33 subjects (13
controls, 20 obese) after an <a
href="https://www.mayoclinic.org/tests-procedures/glucose-challenge-test/about/pac-20394277">oral
glucose challenge</a>. Measurements were taken at baseline (t0), 0.5, 1,
1.5, 2, and 3 hours. Of interest is how the plasma inorganic phosphate
levels differ over time and between the two groups. Fit a sensible
linear mixed-effect model to investigate these questions.</p>
<p>Below we read in the data, provide columns names, and format the
group column as a factor. Notice the data is in “wide” format, with one
record per subject.</p>
<pre class="r"><code>phosphate &lt;- read.table(&quot;data/phosphate.dat&quot;, header = FALSE)
names(phosphate) &lt;- c(&quot;group&quot;, &quot;id&quot;, &quot;t0&quot;, &quot;t0.5&quot;, &quot;t1&quot;, &quot;t1.5&quot;, &quot;t2&quot;, &quot;t3&quot;)
phosphate$group &lt;- factor(phosphate$group, labels = c(&quot;control&quot;, &quot;obese&quot;))
head(phosphate)</code></pre>
<pre><code>##     group id  t0 t0.5  t1 t1.5  t2  t3
## 1 control  1 4.3  3.3 3.0  2.6 2.2 2.5
## 2 control  2 3.7  2.6 2.6  1.9 2.9 3.2
## 3 control  3 4.0  4.1 3.1  2.3 2.9 3.1
## 4 control  4 3.6  3.0 2.2  2.8 2.9 3.9
## 5 control  5 4.1  3.8 2.1  3.0 3.6 3.4
## 6 control  6 3.8  2.2 2.0  2.6 3.8 3.6</code></pre>
<p>Reshaping the data facilitates data visualization. The
<code>pivot_longer()</code> function from the tidyr package makes quick
work of this. <span class="citation">(Wickham and Girlich
2022)</span></p>
<ul>
<li>The <code>names_to = "time"</code> argument moves the column names,
t0 - t3, into a single column called “time”</li>
<li>The <code>names_prefix = "t"</code> argument strips “t” from the
column names that were placed in the “time” column.</li>
<li>The <code>names_transform = list(time = as.numeric)</code> converts
values in the new “time” column to numeric.</li>
<li>The <code>values_to = "level"</code> moves the values under the t0 -
t3 columns into a single column called “level”</li>
</ul>
<pre class="r"><code>library(tidyr)
phosphateL &lt;- pivot_longer(phosphate, cols = t0:t3, 
                           names_to = &quot;time&quot;, 
                           names_prefix = &quot;t&quot;,
                           names_transform = list(time = as.numeric),
                           values_to = &quot;level&quot;)
head(phosphateL, n = 10)</code></pre>
<pre><code>## # A tibble: 10 × 4
##    group      id  time level
##    &lt;fct&gt;   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 control     1   0     4.3
##  2 control     1   0.5   3.3
##  3 control     1   1     3  
##  4 control     1   1.5   2.6
##  5 control     1   2     2.2
##  6 control     1   3     2.5
##  7 control     2   0     3.7
##  8 control     2   0.5   2.6
##  9 control     2   1     2.6
## 10 control     2   1.5   1.9</code></pre>
<p>Now we can use the ggplot2 package <span class="citation">(Wickham
2016)</span> to visualize the data. Below we plot the phosphate
trajectories over time for each subject, with the plots broken out by
group. In addition we add a smooth trend line to each plot to visualize
the “average” trend for each group. There appears to be a great deal of
variability between the subjects within each group. It also looks like
the phosphate levels drop quickly within the first hour for the control
group compared to the obese group.</p>
<pre class="r"><code>library(ggplot2)
ggplot(phosphateL) +
  aes(x = time, y = level, group = id) +
  geom_line() +
  geom_smooth(aes(group = group), se = FALSE, linewidth = 2) +
  facet_wrap(~group)</code></pre>
<p><img src="lme_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>We can also compute simple means by time and group and compare
visually. Below we use <code>aggregate()</code> to compute the means and
then pipe into the ggplot code. Again it appears the phosphate levels
for the control group drop faster and lower than the obese group, though
by hour 3 they seem about the same.</p>
<pre class="r"><code>aggregate(level ~ time + group, data = phosphateL, mean) |&gt;
  ggplot() +
  aes(x = time, y = level, linetype = group) +
  geom_point() +
  geom_line()</code></pre>
<p><img src="lme_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>In both plots it appears the effect of time differs between groups.
Therefore it seems reasonable to allow these terms to interact in our
mixed-effect model.</p>
<p>To fit our models we will use the <code>lmer()</code> function in the
lme4 package <span class="citation">(Bates et al. 2015)</span>. Below we
model level as a function of time, group, and their interaction. We also
fit a random intercept for each subject using the syntax
<code>(1|id:group)</code>. The reason we use <code>id:group</code> is
because the id numbers are nested within each group. This creates 33
separate id groups. The summary output shows a fairly large t value for
the interaction, which provides good evidence that the interaction is
reliably negative. (The summary output for lmer models does not display
p values since the null distributions for the t values are unknown for
unbalanced data.)</p>
<pre class="r"><code>library(lme4)
m &lt;- lmer(level ~ time * group + (1|id:group), data = phosphateL)
summary(m, corr = FALSE)</code></pre>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: level ~ time * group + (1 | id:group)
##    Data: phosphateL
## 
## REML criterion at convergence: 389.6
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -2.34465 -0.60816 -0.08669  0.56476  2.25586 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  id:group (Intercept) 0.2762   0.5255  
##  Residual             0.2934   0.5416  
## Number of obs: 198, groups:  id:group, 33
## 
## Fixed effects:
##                 Estimate Std. Error       df t value Pr(&gt;|t|)    
## (Intercept)       3.4201     0.1785  49.6845  19.154  &lt; 2e-16 ***
## time             -0.1776     0.0622 163.0000  -2.855 0.004863 ** 
## groupobese        0.8819     0.2294  49.6845   3.845 0.000344 ***
## time:groupobese  -0.2364     0.0799 163.0000  -2.959 0.003546 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Before we use or interpret this model we should assess the residuals
vs fitted value plot. We can create this plot by simply calling
<code>plot()</code> on the model object. We would like to see a uniform
distribution of residuals hovering closely around 0. This plot looks OK
until our fitted values exceed 4.0, at which point we begin to
under-predict. Most of the residuals are positive in this range,
indicating our model-fitted values are systematically smaller than what
we observed.</p>
<pre class="r"><code>plot(m)</code></pre>
<p><img src="lme_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>The model we fit assumes the effect of time is <em>linear</em>, and
that the linear effect of time changes for each group. We can visualize
the model using the ggeffects package <span class="citation">(Lüdecke
2018)</span>. With the data added we can see that linear effects seem to
simplistic.</p>
<pre class="r"><code>library(ggeffects)
ggeffect(m, terms = c(&quot;time&quot;, &quot;group&quot;)) |&gt;
  plot(add.data = TRUE, jitter = 0)</code></pre>
<p><img src="lme_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Given our exploratory plots we may want to entertain a
<em>non-linear</em> effect of time. One way to do this is with natural
cubic splines. Using the splines package <span class="citation">(R Core
Team 2022)</span>, we can specify that we want to allow the trajectory
of time to change directions twice using the syntax
<code>ns(time, df = 2)</code>. We skip summarizing the model and look at
the residuals vs fitted value plot. This looks better than the previous
plot, though it still exhibits some under-predicting in the higher end
of the fitted values.</p>
<pre class="r"><code>library(splines)
m2 &lt;- lmer(level ~ ns(time, df = 2) * group + (1|group:id), 
           data = phosphateL)
plot(m2)</code></pre>
<p><img src="lme_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>We can compare the models’ AIC values to assess whether the more
complicated model is better. Recall that lower AIC values suggest a
model will perform better on out-of-sample data. It appears the model
with non-linear effects is a good deal better than the model with linear
effects. The df column refers to the number of parameters in the
model.</p>
<pre class="r"><code>AIC(m, m2)</code></pre>
<pre><code>##    df      AIC
## m   6 401.6025
## m2  8 321.0661</code></pre>
<p>The non-linear model is better than the original linear model. But is
the non-linear model a <em>good</em> model? One way to assess this is to
simulate data using the model and see how it compares to the original
data. Below we use the <code>simulate()</code> function to simulate 50
sets of phosphate values from our non-linear model. Next we plot a
smooth histogram of the observed data. Then we loop through the
simulated data and plot a smooth histogram for each simulation. What we
see is that our model is generating data that looks pretty similar to
our original data. It’s not perfect, and we wouldn’t want it to be, but
it looks good enough.</p>
<pre class="r"><code>sim1 &lt;- simulate(m2, nsim = 50)
plot(density(phosphateL$level), ylim = c(0, 0.6))
for(i in 1:50)lines(density(sim1[[i]]), col = &quot;grey90&quot;)</code></pre>
<p><img src="lme_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>As before, let’s use ggeffects to visualize our model. We see the
bend in our fitted lines due to our non-linear model.</p>
<pre class="r"><code>ggeffect(m2, terms = c(&quot;time&quot;, &quot;group&quot;)) |&gt;
  plot(add.data = TRUE, jitter = 0)</code></pre>
<p><img src="lme_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>Looking at the summary for model m2 reveals coefficients that are
impossible to interpret. This is one of the drawbacks of models with
non-linear effects. However we see under the Random effects section that
there is more variation between subjects (0.54) than within subjects
(0.42). This probably makes biological sense.</p>
<pre class="r"><code>summary(m2, corr = FALSE)</code></pre>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: level ~ ns(time, df = 2) * group + (1 | group:id)
##    Data: phosphateL
## 
## REML criterion at convergence: 305.1
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.3481 -0.5403  0.0777  0.5780  2.8434 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  group:id (Intercept) 0.2953   0.5434  
##  Residual             0.1787   0.4227  
## Number of obs: 198, groups:  group:id, 33
## 
## Fixed effects:
##                               Estimate Std. Error        df t value Pr(&gt;|t|)
## (Intercept)                    3.97849    0.18217  53.50768  21.839  &lt; 2e-16
## ns(time, df = 2)1             -2.20405    0.24410 161.00000  -9.029 5.08e-16
## ns(time, df = 2)2              0.21989    0.13821 161.00000   1.591   0.1136
## groupobese                     0.59564    0.23401  53.50768   2.545   0.0138
## ns(time, df = 2)1:groupobese   0.03403    0.31355 161.00000   0.109   0.9137
## ns(time, df = 2)2:groupobese  -0.90276    0.17753 161.00000  -5.085 1.01e-06
##                                 
## (Intercept)                  ***
## ns(time, df = 2)1            ***
## ns(time, df = 2)2               
## groupobese                   *  
## ns(time, df = 2)1:groupobese    
## ns(time, df = 2)2:groupobese ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Judging from the effect display the interaction in the model is
warranted, but we can formally test and verify this using the
<code>Anova()</code> function in the car package <span
class="citation">(Fox and Weisberg 2019)</span>. The large chi-square
statistic and small p-value confirm this.</p>
<pre class="r"><code>library(car)
Anova(m2)</code></pre>
<pre><code>## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: level
##                           Chisq Df Pr(&gt;Chisq)    
## ns(time, df = 2)       205.0647  2  &lt; 2.2e-16 ***
## group                    7.7832  1   0.005273 ** 
## ns(time, df = 2):group  26.8095  2  1.508e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Since we have both non-linear effects and interactions, there is no
convenient interpretation of our model parameters. However we can use
our model to make predictions at levels of interest and then compare the
expected values. For example, what is the expected difference in
phosphate values between control and obese subjects at 1 hour post
glucose challenge? We can answer this using the emmeams package <span
class="citation">(Lenth 2022)</span>. Below we specify we want to use m2
and compare groups at time = 1, and then pipe into the
<code>confint()</code> function for a 95% confidence interval on the
difference. (We can disregard the note about interactions since we
specified the time.) The output indicates an estimated difference of
about -0.83 with a 95% CI of [-1.26, -0.40].</p>
<pre class="r"><code>library(emmeans)
emmeans(m2, specs = pairwise ~ group, at = list(time = 1)) |&gt;
  confint()</code></pre>
<pre><code>## $emmeans
##  group   emmean    SE df lower.CL upper.CL
##  control   2.88 0.164 36     2.55     3.21
##  obese     3.71 0.132 36     3.44     3.98
## 
## Degrees-of-freedom method: kenward-roger 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast        estimate    SE df lower.CL upper.CL
##  control - obese   -0.832 0.211 36    -1.26   -0.404
## 
## Degrees-of-freedom method: kenward-roger 
## Confidence level used: 0.95</code></pre>
</div>
<div id="references" class="section level3 unnumbered">
<h3 class="unnumbered">References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-lme4" class="csl-entry">
Bates, Douglas, Martin Mächler, Ben Bolker, and Steve Walker. 2015.
<span>“Fitting Linear Mixed-Effects Models Using <span
class="nocase">lme4</span>.”</span> <em>Journal of Statistical
Software</em> 67 (1): 1–48. <a
href="https://doi.org/10.18637/jss.v067.i01">https://doi.org/10.18637/jss.v067.i01</a>.
</div>
<div id="ref-davis" class="csl-entry">
Davis, Charles S. 2002. <em>Statistical Methods for the Analysis of
Repeated Measurements</em>. Springer, New York.
</div>
<div id="ref-faraway_book" class="csl-entry">
Faraway, Julian. 2006. <em>Extending the Linear Model with
<span>R</span></em>. CRC press. <a
href="https://julianfaraway.github.io/faraway/ELM/">https://julianfaraway.github.io/faraway/ELM/</a>.
</div>
<div id="ref-faraway" class="csl-entry">
———. 2016. <em>Faraway: Functions and Datasets for Books by Julian
Faraway</em>. <a
href="https://CRAN.R-project.org/package=faraway">https://CRAN.R-project.org/package=faraway</a>.
</div>
<div id="ref-car" class="csl-entry">
Fox, John, and Sanford Weisberg. 2019. <em>An <span>R</span> Companion
to Applied Regression</em>. Third. Thousand Oaks <span>CA</span>: Sage.
<a
href="https://socialsciences.mcmaster.ca/jfox/Books/Companion/">https://socialsciences.mcmaster.ca/jfox/Books/Companion/</a>.
</div>
<div id="ref-emmeans" class="csl-entry">
Lenth, Russell V. 2022. <em>Emmeans: Estimated Marginal Means, Aka
Least-Squares Means</em>. <a
href="https://CRAN.R-project.org/package=emmeans">https://CRAN.R-project.org/package=emmeans</a>.
</div>
<div id="ref-ggeffects" class="csl-entry">
Lüdecke, Daniel. 2018. <span>“Ggeffects: Tidy Data Frames of Marginal
Effects from Regression Models.”</span> <em>Journal of Open Source
Software</em> 3 (26): 772. <a
href="https://doi.org/10.21105/joss.00772">https://doi.org/10.21105/joss.00772</a>.
</div>
<div id="ref-R" class="csl-entry">
R Core Team. 2022. <em>R: A Language and Environment for Statistical
Computing</em>. Vienna, Austria: R Foundation for Statistical Computing.
<a href="https://www.R-project.org/">https://www.R-project.org/</a>.
</div>
<div id="ref-west2015" class="csl-entry">
West, Brady T., Kathleen B. Welch, and Andrzej T. Galecki. 2015.
<em>Linear Mixed Models, 2nd Ed.</em> Boca Raton: <span>CRC</span>
Press.
</div>
<div id="ref-ggplot2" class="csl-entry">
Wickham, Hadley. 2016. <em>Ggplot2: Elegant Graphics for Data
Analysis</em>. Springer-Verlag New York. <a
href="https://ggplot2.tidyverse.org">https://ggplot2.tidyverse.org</a>.
</div>
<div id="ref-tidyr" class="csl-entry">
Wickham, Hadley, and Maximilian Girlich. 2022. <em>Tidyr: Tidy Messy
Data</em>. <a
href="https://CRAN.R-project.org/package=tidyr">https://CRAN.R-project.org/package=tidyr</a>.
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
