<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Logistic Regression Models</title>

<script src="site_libs/header-attrs-2.16/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/readable.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>





<style type="text/css">
/* for pandoc --citeproc since 2.11 */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Statistical Modeling Examples in R</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Examples
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="lm.html">linear models</a>
    </li>
    <li>
      <a href="lrm.html">logistic regression models</a>
    </li>
    <li>
      <a href="cm.html">count models</a>
    </li>
    <li>
      <a href="lme.html">mixed-effect models</a>
    </li>
  </ul>
</li>
<li>
  <a href="about.html">About</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Logistic Regression Models</h1>

</div>


<div id="logistic-regression-with-no-predictors-intercept-only"
class="section level3">
<h3>Logistic regression with no predictors (intercept only)</h3>
<p>100 Hershey’s Kisses are put into a large cup and dumped on a table.
We want to estimate the proportion of Kisses we can expect to land on
their base. <span class="citation">(Bilder and Loughin 2015)</span> In
our experiment we observe 39 out of 100. What is the 95% confidence
interval on the proportion?</p>
<pre class="r"><code>prop.test(x = 39, n = 100)</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  39 out of 100, null probability 0.5
## X-squared = 4.41, df = 1, p-value = 0.03573
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.2955674 0.4929886
## sample estimates:
##    p 
## 0.39</code></pre>
<p>To get just the confidence interval:</p>
<pre class="r"><code>pout &lt;- prop.test(x = 39, n = 100)
pout$conf.int</code></pre>
<pre><code>## [1] 0.2955674 0.4929886
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<p>This can be analyzed as an intercept-only binary logistic regression
model. The confidence interval is slightly different.</p>
<pre class="r"><code>m &lt;- glm(cbind(39, 100-39) ~ 1, family = binomial)
plogis(confint(m))</code></pre>
<pre><code>##     2.5 %    97.5 % 
## 0.2980745 0.4874909</code></pre>
<p>There are many confidence intervals that can be calculated for
proportions. The binom package calculates 11 of them. <span
class="citation">(Dorai-Raj 2022)</span></p>
<pre class="r"><code>library(binom)
binom.confint(x = 39, n = 100)</code></pre>
<pre><code>##           method  x   n      mean     lower     upper
## 1  agresti-coull 39 100 0.3900000 0.3000839 0.4880547
## 2     asymptotic 39 100 0.3900000 0.2944028 0.4855972
## 3          bayes 39 100 0.3910891 0.2972462 0.4861311
## 4        cloglog 39 100 0.3900000 0.2947601 0.4839396
## 5          exact 39 100 0.3900000 0.2940104 0.4926855
## 6          logit 39 100 0.3900000 0.2996112 0.4886334
## 7         probit 39 100 0.3900000 0.2985837 0.4879698
## 8        profile 39 100 0.3900000 0.2980814 0.4874917
## 9            lrt 39 100 0.3900000 0.2980690 0.4875128
## 10     prop.test 39 100 0.3900000 0.2955674 0.4929886
## 11        wilson 39 100 0.3900000 0.3001687 0.4879698</code></pre>
<p>The “prop.test” and “profile” versions are the two we calculated
above.</p>
</div>
<div id="logistic-regression-with-numeric-predictors-1"
class="section level3">
<h3>Logistic regression with numeric predictors (1)</h3>
<p>The <code>malaria</code> data frame from the ISwR package has 100
rows and 4 columns. It contains data on a sample of 100 children aged
3–15 years from a village in Ghana. Based on observations during the
study period, the children were categorized into two groups: individuals
with and without symptoms of malaria. Model the risk of malaria
(<code>mal</code>) as a function of age (<code>age</code>) and
log-transformed antibody levels (<code>log(ab)</code>). <span
class="citation">(Dalgaard 2020)</span></p>
<pre class="r"><code>library(ISwR)
data(&quot;malaria&quot;)</code></pre>
<p>To start, let’s take a quick look at the summary of the data using
the <code>summary()</code> function:</p>
<pre class="r"><code>summary(malaria)</code></pre>
<pre><code>##     subject            age              ab              mal      
##  Min.   :  1.00   Min.   : 3.00   Min.   :   2.0   Min.   :0.00  
##  1st Qu.: 25.75   1st Qu.: 5.75   1st Qu.:  29.0   1st Qu.:0.00  
##  Median : 50.50   Median : 9.00   Median : 111.0   Median :0.00  
##  Mean   : 50.50   Mean   : 8.86   Mean   : 311.5   Mean   :0.27  
##  3rd Qu.: 75.25   3rd Qu.:12.00   3rd Qu.: 373.8   3rd Qu.:1.00  
##  Max.   :100.00   Max.   :15.00   Max.   :2066.0   Max.   :1.00</code></pre>
<p>Looking at the summary, we can see that mal takes the values 0 and 1.
The mean of mal is 0.27, which indicates that 27% of the data take the
value 1, meaning 27% of children monitored showed symptoms of
malaria.</p>
<p>We can see that age ranges from 3 to 15 and is slightly left-skewed.
We can tell the skewness by comparing the median to the mean. Here, the
median, 9.00, is slightly larger than the mean, 8.86. This indicates
that more of the data is below the mean – the distribution is pulled out
to the left, meaning there are slightly more younger children in this
dataset.</p>
<p>From the summary we can also see that ab is very skewed, but in the
opposite direction as age. Ab represents the antibody levels of the
subjects and ranges from 2.0 to 2066.0. The median of ab, 111.0, is much
smaller than the mean, 311.5. This indicates that ab is right-skewed. If
we look at the 3rd quantile, we can see that 75% of the data is below
373.8. The maximum value of 2066.0 is much much larger than the 3rd
quantile value, which may hint that the 2066.0 could be an outlier.</p>
<p>Looking at a box plot of the ab can give us a good visualization of
this skewness and spread of the data. Here we plot the distribution of
ab by mal and log(ab) by mal.</p>
<pre class="r"><code>boxplot(ab ~ mal, data = malaria)</code></pre>
<p><img src="lrm_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>boxplot(log(ab) ~ mal, data = malaria)</code></pre>
<p><img src="lrm_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
<p>In the first box plot (ab by mal), because of the spread of the data,
it appears very sqiushed and hard to interpret. We can see that children
who did show symptoms of malaria (mal = 1) tend to have a lower antibody
count while those who did not show symptoms (mal = 0) tend to have a
higher antibody count. We can also see the right-skewness of the
data.</p>
<p>The log transformed ab data is much clearer. We can see that same
trend of lower antibody count for those who showed symptoms of malaria.
With this plot we can get a feel for the values of the data: for those
who showed no symptoms of malaria, we can see that 50% of the data falls
between log(ab) = 4 and 6, whereas 50% of the data for those who did
show symptoms of malaria falls between about log(ab) = 3 and 4.</p>
<p>We can also look at how age varies based on malaria symptoms:</p>
<pre class="r"><code>library(ggplot2)

malaria$group = ifelse(malaria$mal == 0, &#39;no symptoms&#39;, &#39;symptoms&#39;)

ggplot(malaria, aes(x=age, fill = group)) + geom_histogram(binwidth=1, color=&quot;black&quot;,) + scale_fill_manual(values = c(&#39;no symptoms&#39; = &#39;gray&#39;, &#39;symptoms&#39; = &#39;cornflowerblue&#39;))</code></pre>
<p><img src="lrm_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>#+ geom_histogram(binwidth=1, color=&quot;black&quot;, fill=&quot;white&quot;)

#boxplot(age ~ mal, data = malaria)</code></pre>
<p>From the histogram, we can see that the ages of subjects are more or
less uniformly spread from 3 to 15. From the box plot, we can see that
subjects who showed symptoms of malaria tended to be of a younger
age.</p>
<p>Now let’s build our model. We will use the <code>glm()</code>
function. <code>glm()</code> is used to fit a generalized linear model
to the data. To specify logistic regression, in the argument we set the
<code>family = binomial(link = "logit")</code>.</p>
<pre class="r"><code>lrm &lt;- glm(mal ~ age + log(ab), family = binomial(link = &quot;logit&quot;), data = malaria)</code></pre>
<p>Now we look at a summary of the model:</p>
<pre class="r"><code>summary(lrm)</code></pre>
<pre><code>## 
## Call:
## glm(formula = mal ~ age + log(ab), family = binomial(link = &quot;logit&quot;), 
##     data = malaria)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.8492  -0.7536  -0.4838   0.8809   2.5796  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  2.57234    0.95184   2.702 0.006883 ** 
## age         -0.06546    0.06772  -0.967 0.333703    
## log(ab)     -0.68235    0.19552  -3.490 0.000483 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 116.652  on 99  degrees of freedom
## Residual deviance:  98.017  on 97  degrees of freedom
## AIC: 104.02
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>We can also look at the model coefficients and confidence
intervals.</p>
<pre class="r"><code>lrm$coefficients</code></pre>
<pre><code>## (Intercept)         age     log(ab) 
##  2.57233727 -0.06546061 -0.68235363</code></pre>
<pre class="r"><code>confint(lrm)</code></pre>
<pre><code>##                  2.5 %     97.5 %
## (Intercept)  0.7810426  4.5452306
## age         -0.2024576  0.0655621
## log(ab)     -1.0985294 -0.3239378</code></pre>
<p>If we look at the confidence intervals for the coefficients in our
model, we can see reasonable ranges of values for the coefficients. The
reasonable range of values for the age coefficient is -0.202 to 0.066.
Note this range is small and includes 0, which implies that the effect
of age on mal is small and we can’t be sure if the effect is positive or
negative.</p>
<p>The reasonable range of values for log(ab) is -1.099 to -0.324. This
range is larger than that of age and is entirely negative. This
indicates that antibody count has a stronger effect on mal than age and
is a negative effect. In other words, lower antibody count is associated
with higher risk of malaria. We can exponentiate this confidence
interval to get odds ratios.</p>
<pre class="r"><code>exp(confint(lrm)[&quot;log(ab)&quot;,])</code></pre>
<pre><code>##     2.5 %    97.5 % 
## 0.3333609 0.7232952</code></pre>
<p>If we wanted to, we could have split the data into training and
testing data:</p>
<pre class="r"><code>set.seed(1)  # make reproducible
i &lt;- sample(x = nrow(malaria), size = 0.75*floor(nrow(malaria)))
malaria.train &lt;- malaria[i,]
malaria.test &lt;- malaria[-i,]</code></pre>
<p>We can then test our model on the training data and see how well it
performs.</p>
<pre class="r"><code>prediction &lt;- predict(lrm, newdata = malaria.test, type=&quot;response&quot;)</code></pre>
</div>
<div id="logistic-regression-with-numeric-predictors-2"
class="section level3">
<h3>Logistic regression with numeric predictors (2)</h3>
<p>The <code>pima</code> data frame from the faraway package contains
data on 768 adult female Pima Indians living near Phoenix <span
class="citation">(Faraway 2016)</span>. This data was collected by <a
href="https://www.niddk.nih.gov/">The National Institute of Diabetes and
Digestive and Kidney Diseases</a>. The purpose of the study was to
investigate factors related to diabetes. The variable <code>test</code>
indicates whether the patient showed signs of diabetes (coded 0 if
negative, 1 if positive). Model <code>test</code> as a function of all
other predictors.</p>
<pre class="r"><code>library(faraway)
data(&quot;pima&quot;)</code></pre>
<p>What is the difference in odds of testing positive for diabetes for a
subject with BMI in the first quartile compared to a subject with BMI at
the third quartile? <span class="citation">(Faraway 2006)</span></p>
<pre class="r"><code>library(emmeans)
bmi_vals &lt;- quantile(pima$bmi, probs = c(0.25,0.75))
rg &lt;- ref_grid(m, at = list(bmi = bmi_vals))
emmeans(rg, specs = &quot;bmi&quot;, type = &quot;response&quot;) |&gt;
  contrast(&quot;pairwise&quot;)</code></pre>
</div>
<div id="ordered-logistic-regression" class="section level3">
<h3>Ordered logistic regression</h3>
<p>The <code>Vietnam</code> data frame in the vcdExtra package <span
class="citation">(Friendly 2022)</span> contains survey data from 1967
on student opinions of the Vietnam War. Students were asked to indicate
which policy out of A, B, C or D they supported. The response categories
were:</p>
<ul>
<li>A: Defeat North Vietnam by widespread bombing and land invasion</li>
<li>B: Maintain the present policy</li>
<li>C: De-escalate military activity, stop bombing and begin
negotiations</li>
<li>D: Withdraw military forces Immediately</li>
</ul>
<p>These are ordered levels, moving from very pro-war (A) to anti-war
(D). Fit a proportional odds model to the data, modeling
<code>response</code> as a function of <code>sex</code>,
<code>year</code>, and their interaction. <span
class="citation">(Friendly and Meyer 2016)</span> (<code>year</code> is
an integer ranging from 1 - 5, corresponding to Freshmen, Sophomore,
Junior, Senior, and Grad student.)</p>
<pre class="r"><code>library(vcdExtra)
data(&quot;Vietnam&quot;)</code></pre>
<p>This will require using the <code>weights</code> argument with the
<code>polr()</code> function. <span class="citation">(Venables and
Ripley 2002)</span></p>
</div>
<div id="references" class="section level3 unnumbered">
<h3 class="unnumbered">References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-bilder2015" class="csl-entry">
Bilder, Christopher R., and Thomas M. Loughin. 2015. <em>Analysis of
Categorical Data in <span>R</span></em>. Boca Raton: <span>CRC</span>
Press.
</div>
<div id="ref-ISwR" class="csl-entry">
Dalgaard, Peter. 2020. <em>ISwR: Introductory Statistics with
<span>R</span></em>. <a
href="https://CRAN.R-project.org/package=ISwR">https://CRAN.R-project.org/package=ISwR</a>.
</div>
<div id="ref-binom" class="csl-entry">
Dorai-Raj, Sundar. 2022. <em>Binom: Binomial Confidence Intervals for
Several Parameterizations</em>. <a
href="https://CRAN.R-project.org/package=binom">https://CRAN.R-project.org/package=binom</a>.
</div>
<div id="ref-faraway_book" class="csl-entry">
Faraway, Julian. 2006. <em>Extending the Linear Model with
<span>R</span></em>. CRC press. <a
href="https://julianfaraway.github.io/faraway/ELM/">https://julianfaraway.github.io/faraway/ELM/</a>.
</div>
<div id="ref-faraway" class="csl-entry">
———. 2016. <em>Faraway: Functions and Datasets for Books by Julian
Faraway</em>. <a
href="https://CRAN.R-project.org/package=faraway">https://CRAN.R-project.org/package=faraway</a>.
</div>
<div id="ref-vcdextra" class="csl-entry">
Friendly, Michael. 2022. <em>vcdExtra: ’Vcd’ Extensions and
Additions</em>. <a
href="https://CRAN.R-project.org/package=vcdExtra">https://CRAN.R-project.org/package=vcdExtra</a>.
</div>
<div id="ref-friendly2016" class="csl-entry">
Friendly, Michael, and David Meyer. 2016. <em>Discrete Data Analysis
with <span>R</span></em>. Boca Raton: <span>CRC</span> Press.
</div>
<div id="ref-MASS" class="csl-entry">
Venables, W. N., and B. D. Ripley. 2002. <em>Modern Applied Statistics
with s</em>. Fourth. New York: Springer. <a
href="https://www.stats.ox.ac.uk/pub/MASS4/">https://www.stats.ox.ac.uk/pub/MASS4/</a>.
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
